/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemutvecklingsprojektet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Julius
 */
public class AgentInlogg extends javax.swing.JFrame {

   private static InfDB idb;
   
    public AgentInlogg(InfDB idb) {
        initComponents();
        this.idb=idb;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RubrikAgentLoggaIn = new javax.swing.JLabel();
        Användarnamn = new javax.swing.JTextField();
        Lösenord = new javax.swing.JTextField();
        RubrikAnvändarnamn = new javax.swing.JLabel();
        RubrikLösenord = new javax.swing.JLabel();
        LoggaInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 281));

        RubrikAgentLoggaIn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RubrikAgentLoggaIn.setText("Agent");

        Användarnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnvändarnamnActionPerformed(evt);
            }
        });

        Lösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LösenordActionPerformed(evt);
            }
        });

        RubrikAnvändarnamn.setText("Användarnamn");

        RubrikLösenord.setText("Lösenord");

        LoggaInButton.setText("Logga in");
        LoggaInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoggaInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RubrikAgentLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RubrikAnvändarnamn)
                        .addComponent(Användarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RubrikLösenord)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(LoggaInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(RubrikAgentLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RubrikAnvändarnamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Användarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RubrikLösenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoggaInButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnvändarnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnvändarnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnvändarnamnActionPerformed

    private void LösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LösenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LösenordActionPerformed

    private void LoggaInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoggaInButtonActionPerformed
        
       try {
         
        String query = "SELECT LOSENORD FORM AGENT WHERE NAMN = '"+Användarnamn.getText()+"'";
        String losen =idb.fetchSingle(query);
        if(losen.equals(Lösenord.getText())){
            new HejAgent().setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null,"Fel Lösenord");
        }
        String agentLösenord = "select lösenord from agent";
        
       // ArrayList<String> allaAgentAnvändarnamn;
       // ArrayList<String> allaAgentLösenord;
        
       // allaAgentAnvändarnamn = new ArrayList<>();
       // allaAgentLösenord = new ArrayList<>();
       }
            
       catch(InfException undantag){
                    JOptionPane.showMessageDialog(null, "Fel användarnamn eller lösenord");
                        System.out.println("Error" + undantag.getMessage());
                    }
        
           
    
       
       // { 
       //int i = 0;
       //boolean matchning = false;
       
       //while(i < allaAgentLösenord.size() && matchning == false)
       //{
         //  String lösenordet = allaAgentLösenord.get(i);
          // if(Lösenord.getText().equals(lösenordet))
           //{
          //    matchning = true;
          // }
          // else
          // {
            //   i++;
           //}
            
       //}
       //if(matchning == true)
       //{
        //   int i2 = 0;
         //  boolean matchning2 = false;
           
         //  while(i2 < allaAgentAnvändarnamn.size() && matchning2 == false)
          // {
           //    String användarnamnet = allaAgentAnvändarnamn.get(i2);
             //  if(Användarnamn.getText().equals(användarnamnet))
             //  {
             //      matchning2 = true;
              //     new HejAgent().setVisible(true);
              // }
           //    else
           //   {
           //        i2++;
            //   }
           //}
           
           
           
           
      // }
       
       
            
        //    allaAgentAnvändarnamn = idb.fetchColumn(agentAnvändarnamn);
        //    allaAgentLösenord = idb.fetchColumn(agentLösenord);
            
         //   if(Användarnamn.getText().equals(agentAnvändarnamn) && Lösenord.getText().equals(agentLösenord))
          //  {
          //  new HejAgent().setVisible(true);
                
         //   } 
        //}     
       //}
    
        
    }//GEN-LAST:event_LoggaInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentInlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentInlogg().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Användarnamn;
    private javax.swing.JButton LoggaInButton;
    private javax.swing.JTextField Lösenord;
    private javax.swing.JLabel RubrikAgentLoggaIn;
    private javax.swing.JLabel RubrikAnvändarnamn;
    private javax.swing.JLabel RubrikLösenord;
    // End of variables declaration//GEN-END:variables
}
