 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemutvecklingsprojektet;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;


// *
// * @author almahedengren
// */

import javax.swing.JOptionPane;
public class AllInformationEnAlien extends javax.swing.JFrame {

    private InfDB idb;
    private ArrayList<String> allaAliens;
    /**
     * Creates new form AllInformationEnAlien
     */
    public AllInformationEnAlien(InfDB idb) {
        initComponents();
        this.idb=idb;
        allaAliens = new ArrayList<>();
        fyllILista();

    }

    /**
     * FyllILista metoden fyller vår comboBox med värden. Värdena är från den databas som vi ska använda oss av dessa får vi 
     * tag på genom att använda oss av sql frågor i vår javakod. 
     */
    
    private void fyllILista()
    {
        
        try {
        String fraga = "select Namn from alien";
        ArrayList<String> svar = idb.fetchColumn(fraga);
        ComboBoxVäljAlien.removeAllItems();
        ComboBoxVäljAlien.addItem("Välj");
        
        for(String värde: svar)
        {
            ComboBoxVäljAlien.addItem(värde);
        }
        }
        catch (InfException undantag){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RubrikVisaAllInfoAlien = new javax.swing.JLabel();
        LabelVäljAlien = new javax.swing.JLabel();
        ComboBoxVäljAlien = new javax.swing.JComboBox<>();
        KnappVälj = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaFönster = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RubrikVisaAllInfoAlien.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        RubrikVisaAllInfoAlien.setForeground(new java.awt.Color(0, 204, 255));
        RubrikVisaAllInfoAlien.setText("Lista all information om en alien");

        LabelVäljAlien.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        LabelVäljAlien.setText("Välj alien:");

        ComboBoxVäljAlien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxVäljAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxVäljAlienActionPerformed(evt);
            }
        });

        KnappVälj.setText("Välj");
        KnappVälj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnappVäljActionPerformed(evt);
            }
        });

        TextAreaFönster.setColumns(20);
        TextAreaFönster.setRows(5);
        jScrollPane2.setViewportView(TextAreaFönster);

        jButton1.setText("<--Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(LabelVäljAlien)
                        .addGap(46, 46, 46)
                        .addComponent(ComboBoxVäljAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KnappVälj, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(105, 105, 105)
                        .addComponent(RubrikVisaAllInfoAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RubrikVisaAllInfoAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KnappVälj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelVäljAlien)
                    .addComponent(ComboBoxVäljAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxVäljAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxVäljAlienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxVäljAlienActionPerformed

    /**
     * Metoden lägger in värden i vår textarea utifrån en alien som man väljer
     * @param evt 
     */
    
    private void KnappVäljActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappVäljActionPerformed
        TextAreaFönster.setText("");
        try
        {
            String query = "Select * from alien where Namn = '" + ComboBoxVäljAlien.getSelectedItem().toString() + "'"; 
            ArrayList<HashMap<String, String>> rad = idb.fetchRows(query);
            
            TextAreaFönster.append(("Alien_ID") + "\t");
            TextAreaFönster.append(("Registreringsdatum") + "\t");
            TextAreaFönster.append(("Losenord") + "\t");
            TextAreaFönster.append(("Namn") + "\t");
            TextAreaFönster.append(("Telefon") + "\t");
            TextAreaFönster.append(("Plats") + "\t");
            TextAreaFönster.append(("Ansvarig_Agent") + "\n");
            
            for(HashMap kolumn : rad)
            {
             
                   TextAreaFönster.append(kolumn.get("Alien_ID") + "\t");
                   TextAreaFönster.append(kolumn.get("Registreringsdatum") + "\t\t");
                   TextAreaFönster.append(kolumn.get("Losenord") + "\t");
                   TextAreaFönster.append(kolumn.get("Namn") + "\t");
                   TextAreaFönster.append(kolumn.get("Telefon") + "\t");
                   TextAreaFönster.append(kolumn.get("Plats") + "\t");
                   TextAreaFönster.append(kolumn.get("Ansvarig_Agent") + "\n");

                }
            }
        
        
        catch(InfException undantag)
        {
            JOptionPane.showMessageDialog(null, "Ange ett giltigt namn");
            System.out.println("Error" + undantag.getMessage());
        }
    }//GEN-LAST:event_KnappVäljActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (HejAgent.getTillbakaKnapp()) {
            new AllInformationEnAlien(idb).setVisible(true);
            dispose();
        } else {
            new HejAgent(idb).setVisible(true);
            dispose();
          }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AllInformationEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AllInformationEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AllInformationEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AllInformationEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AllInformationEnAlien().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxVäljAlien;
    private javax.swing.JButton KnappVälj;
    private javax.swing.JLabel LabelVäljAlien;
    private javax.swing.JLabel RubrikVisaAllInfoAlien;
    private javax.swing.JTextArea TextAreaFönster;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
