/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemutvecklingsprojektet;

import oru.inf.InfDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author almahedengren
 */
public class GeAdministratörStatus extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form GeAdministratörStatus
     */
    public GeAdministratörStatus(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllILista();
        LabelGodkänd.setVisible(false);

    }

    public void fyllILista() {
        try {
            ComboBoxVäljAgent.removeAllItems();
            ComboBoxVäljAgent.addItem("välj");
            String fraga = "select namn from agent";
            ArrayList<String> svar = idb.fetchColumn(fraga);

            for (String värde : svar) {
                ComboBoxVäljAgent.addItem(värde);
            }
        } catch (InfException undantag) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelVäljAgent = new javax.swing.JLabel();
        ComboBoxVäljAgent = new javax.swing.JComboBox<>();
        RubrikGeAdministratörstatus = new javax.swing.JLabel();
        ButtonOK = new javax.swing.JButton();
        LabelGodkänd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelVäljAgent.setFont(new java.awt.Font("Perpetua", 0, 12)); // NOI18N
        LabelVäljAgent.setText("Välj Agent:");

        ComboBoxVäljAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RubrikGeAdministratörstatus.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        RubrikGeAdministratörstatus.setForeground(new java.awt.Color(0, 204, 255));
        RubrikGeAdministratörstatus.setText("Ge administratörstatus");

        ButtonOK.setText("OK");
        ButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOKActionPerformed(evt);
            }
        });

        LabelGodkänd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelGodkänd.setForeground(new java.awt.Color(0, 204, 51));
        LabelGodkänd.setText("Agenten har blivit administratör!");

        jButton1.setText("<--Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RubrikGeAdministratörstatus)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelVäljAgent)
                        .addGap(47, 47, 47)
                        .addComponent(ComboBoxVäljAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ButtonOK)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelGodkänd, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(21, 21, 21)
                .addComponent(RubrikGeAdministratörstatus)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelVäljAgent)
                    .addComponent(ComboBoxVäljAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelGodkänd)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoden nedan ger en agent som inte är administratör en
     * administratörstatus. Då ändras statusen till bokstaven J
     *
     * @param evt
     */

    private void ButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOKActionPerformed
        try {
            String query = "update agent set administrator = 'J' where namn = '" + ComboBoxVäljAgent.getSelectedItem() + "'";
            idb.update(query);
            LabelGodkänd.setVisible(true);
        } catch (InfException undantag) {
            JOptionPane.showMessageDialog(null, "Error!!");
        }
    }//GEN-LAST:event_ButtonOKActionPerformed

    /**
     * Den här metoden är skriven på tillbakaknapparna som vi har på många av
     * våra sidor. Funktionen på tillbaka knappen är som det låter att genom att
     * trycka på knappen ska man komma tillbaka till föregående sida och den
     * föregående sidan ska med andra ord öppnas.
     *
     * @param evt
     */

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HejAdministrator(idb).setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOK;
    private javax.swing.JComboBox<String> ComboBoxVäljAgent;
    private javax.swing.JLabel LabelGodkänd;
    private javax.swing.JLabel LabelVäljAgent;
    private javax.swing.JLabel RubrikGeAdministratörstatus;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
