/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemutvecklingsprojektet;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author alval
 */
public class ListaAliensRas extends javax.swing.JFrame {
    private InfDB idb;
    
    /**
     * Creates new form ListaAliens
     */
    public ListaAliensRas(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllILista();

        
        
    }
    
     private void fyllILista() 
    {
        
        
//        try
//        {
            
        
        ListaVäljRas.removeAllItems();
        ListaVäljRas.addItem("Välj");
        ListaVäljRas.addItem("Boglodite");
        ListaVäljRas.addItem("Squid");
        ListaVäljRas.addItem("Worm");
        
//
//       String query = "SELECT namn from alien";
//        ArrayList<String> resultat = idb.fetchColumn(query);
//        
//        for(String värde : resultat)
//        {
//            ListaVäljRas.addItem(värde);
//        }
     }
//        
//        catch(InfException e)
//        {
//            JOptionPane.showMessageDialog(null, "Error");
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RubrikVisaRas = new javax.swing.JLabel();
        LabelVäljRas = new javax.swing.JLabel();
        ListaVäljRas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaFörRas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RubrikVisaRas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RubrikVisaRas.setText("Visa ras av alien");

        LabelVäljRas.setText("Välj ras:");

        ListaVäljRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaVäljRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVäljRasActionPerformed(evt);
            }
        });

        TextAreaFörRas.setColumns(20);
        TextAreaFörRas.setRows(5);
        jScrollPane1.setViewportView(TextAreaFörRas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RubrikVisaRas, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelVäljRas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(ListaVäljRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RubrikVisaRas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaVäljRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelVäljRas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaVäljRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVäljRasActionPerformed
        
        try {
            
      
         if(ListaVäljRas.getSelectedItem().equals("Boglodite")){
            String query = "select alien.alien_id, alien.namn, boglodite.Antal_Boogies from alien join Boglodite on alien.alien_id = boglodite.Alien_ID";
            ArrayList<HashMap<String, String>> rader = idb.fetchRows(query);
            TextAreaFörRas.setText(null);
            
            for(HashMap kolumn : rader){
            TextAreaFörRas.append(kolumn.get("Alien_ID") + "\t");
            TextAreaFörRas.append(" " + kolumn.get("Namn") + "\t");
            TextAreaFörRas.append(" " + kolumn.get("Antal_Boogies") + "\n");
            
            }
        }else if(ListaVäljRas.getSelectedItem().equals("Squid")){
            String query = "select alien.alien_id, alien.namn, squid.Antal_Armar from alien join Squid on alien.Alien_ID = squid.Alien_ID";
            ArrayList<HashMap<String, String>> rader = idb.fetchRows(query);
            TextAreaFörRas.setText(null);
            
            for(HashMap kolumn : rader){
            TextAreaFörRas.append(kolumn.get("Alien_ID") + "\t");
            TextAreaFörRas.append(" " + kolumn.get("Namn") + "\t");
            TextAreaFörRas.append(" " + kolumn.get("Antal_Armar") + "\n");
            }
        }else if (ListaVäljRas.getSelectedItem().equals("Worm")){
            String query = "select alien.Alien_ID, alien.Namn from alien join Worm on alien.Alien_ID = Worm.Alien_ID";
            ArrayList<HashMap<String, String>> rader = idb.fetchRows(query);
            TextAreaFörRas.setText(null);
            
            for(HashMap kolumn : rader){
            TextAreaFörRas.append(kolumn.get("Alien_ID") + "\t");
            TextAreaFörRas.append(" " + kolumn.get("Namn") + "\n");
            }
        }
        } 
        catch(InfException undantag){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_ListaVäljRasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListaAliensRas(idb).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelVäljRas;
    private javax.swing.JComboBox<String> ListaVäljRas;
    private javax.swing.JLabel RubrikVisaRas;
    private javax.swing.JTextArea TextAreaFörRas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
