/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemutvecklingsprojektet;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
/**
 *
 * @author alval
 */
public class ListaAliensPlats extends javax.swing.JFrame {
//    
    private ArrayList<String> lista; 
    private InfDB idb;
  
    /**
     * Creates new form ListaAliensPlats
     */
    public ListaAliensPlats(InfDB idb) 
    {
       initComponents();
       this.idb=idb;
       lista = new ArrayList<>();
       fyllILista();
      
    }
//Fyller i comboboxen med värden, använder sql fråga för att hämta ut information från databasen. 
    
    private void fyllILista() 
    {
        try
        {
     
        ListaVäljPlats.removeAllItems();
        ListaVäljPlats.addItem("Välj");

        String query = "SELECT benamning from plats";
        ArrayList<String> resultat = idb.fetchColumn(query);
        
        for(String värde : resultat)
        {
            ListaVäljPlats.addItem(värde);
        }
        }
        
        catch(InfException undantag)
        {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        RubrikAlienEfterPlats = new javax.swing.JLabel();
        LabelVäljPlats = new javax.swing.JLabel();
        ListaVäljPlats = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaPlatsLista = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RubrikAlienEfterPlats.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        RubrikAlienEfterPlats.setForeground(new java.awt.Color(0, 204, 255));
        RubrikAlienEfterPlats.setText("Visa alien efter plats");

        LabelVäljPlats.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        LabelVäljPlats.setText("Välj plats:");

        ListaVäljPlats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaVäljPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaVäljPlatsActionPerformed(evt);
            }
        });

        TextAreaPlatsLista.setColumns(20);
        TextAreaPlatsLista.setRows(5);
        jScrollPane1.setViewportView(TextAreaPlatsLista);

        jButton2.setText("<--Tillbaka");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(LabelVäljPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ListaVäljPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RubrikAlienEfterPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(RubrikAlienEfterPlats)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(ListaVäljPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelVäljPlats)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Denna metoden hämtar ut information om alien från tabellen alien beroende på vilken plats vi väljer i comboboxen.
//Sedan skriver den ut informationen om alien som finns på den valda platsen i textArean.
    private void ListaVäljPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaVäljPlatsActionPerformed
        
        try
        {
            String query = "select Alien.Alien_ID, Alien.Namn from Alien join Plats on Alien.Plats = Plats.Plats_ID where benamning = '"+ ListaVäljPlats.getSelectedItem()+"'";
            ArrayList<HashMap<String, String>> raden = idb.fetchRows(query);
            TextAreaPlatsLista.setText(null);
            TextAreaPlatsLista.setEditable(false);
            
            TextAreaPlatsLista.append(("Alien_ID") + "\t");
            TextAreaPlatsLista.append(("Namn") + "\n");
            
        for (HashMap kolumn : raden){
           
            
            TextAreaPlatsLista.append(kolumn.get("Alien_ID") + "\t");
            TextAreaPlatsLista.append(" " + kolumn.get("Namn") + "\n");
            TextAreaPlatsLista.setEditable(false);
        } 
        }
        
        catch (InfException undantag){
            JOptionPane.showMessageDialog(null, "Error");
            
        }
    }//GEN-LAST:event_ListaVäljPlatsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (HejAgent.getTillbakaKnapp()) {
            new ListaAliensPlats(idb).setVisible(true);
            dispose();
        } else {
            new HejAgent(idb).setVisible(true);
            dispose();
          }
  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ListaAliensPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ListaAliensPlats(idb).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelVäljPlats;
    private javax.swing.JComboBox<String> ListaVäljPlats;
    private javax.swing.JLabel RubrikAlienEfterPlats;
    private javax.swing.JTextArea TextAreaPlatsLista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
