/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemutvecklingsprojektet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author almahedengren
 */
public class ÄndraRas extends javax.swing.JFrame {
    private InfDB idb;
        /**
     * Creates new form ÄndraRas
     */
    public ÄndraRas(InfDB idb) {
        initComponents();
        this.idb=idb;
        fyllIListaAlien();
        fyllIListaRas();
        LabelRasenHarÄndrats.setVisible(false);
    }

    private void fyllIListaAlien(){
        try {
            ComboBoxVäljAlien.removeAllItems();
            ComboBoxVäljAlien.addItem("Välj");
            String fraga = "select Alien_ID from alien";
            ArrayList<String> svar = idb.fetchColumn(fraga);
        
        for(String värde : svar)
        {
            ComboBoxVäljAlien.addItem(värde);
        }
        }
        catch (InfException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }
    
    private void fyllIListaRas(){
        ComboBoxVäljNyRas.removeAllItems();
        ComboBoxVäljNyRas.addItem("Välj");
        ComboBoxVäljNyRas.addItem("Boglodite");
        ComboBoxVäljNyRas.addItem("Squid");
        ComboBoxVäljNyRas.addItem("Worm");
        
        ComboBoxVäljNuvarandeRas.removeAllItems();
        ComboBoxVäljNuvarandeRas.addItem("Välj");
        ComboBoxVäljNuvarandeRas.addItem("Boglodite");
        ComboBoxVäljNuvarandeRas.addItem("Squid");
        ComboBoxVäljNuvarandeRas.addItem("Worm");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRubrik = new javax.swing.JLabel();
        LabelVäljAlien = new javax.swing.JLabel();
        ComboBoxVäljAlien = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxVäljNyRas = new javax.swing.JComboBox<>();
        ButtonÄndra = new javax.swing.JButton();
        LabelRasenHarÄndrats = new javax.swing.JLabel();
        LabelNuvarandeRas = new javax.swing.JLabel();
        ComboBoxVäljNuvarandeRas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelRubrik.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LabelRubrik.setText("Ändra ras");

        LabelVäljAlien.setText("Välj Alien:");

        ComboBoxVäljAlien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Ny ras:");

        ComboBoxVäljNyRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ButtonÄndra.setText("Ändra");
        ButtonÄndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonÄndraActionPerformed(evt);
            }
        });

        LabelRasenHarÄndrats.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelRasenHarÄndrats.setText("Rasen har ändrats!");

        LabelNuvarandeRas.setText("Nuvarande ras:");

        ComboBoxVäljNuvarandeRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelRubrik)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelRasenHarÄndrats)
                        .addGap(124, 124, 124))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNuvarandeRas)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxVäljNuvarandeRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxVäljNyRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelVäljAlien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(ComboBoxVäljAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(ButtonÄndra)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LabelRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ButtonÄndra))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNuvarandeRas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxVäljNuvarandeRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelVäljAlien)
                            .addComponent(ComboBoxVäljAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxVäljNyRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(LabelRasenHarÄndrats)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonÄndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonÄndraActionPerformed
       try
       {
           
       if(ComboBoxVäljNuvarandeRas.getSelectedItem().equals("Boglodite")){
           String ändring = "DELETE FROM Boglodite where Alien_ID = '" + ComboBoxVäljAlien.getSelectedItem() + "'";           
           idb.delete(ändring);
           
           
           String nyRas = "INSERT INTO " + ComboBoxVäljNyRas.getSelectedItem()+ "(Alien_ID)" + "VALUES" + "('" + ComboBoxVäljAlien.getSelectedItem()+ "')";
           idb.insert(nyRas);
       }
       if(ComboBoxVäljNuvarandeRas.getSelectedItem().equals("Worm")){
          String ändring = "DELETE FROM Worm where Alien_ID = '" + ComboBoxVäljAlien.getSelectedItem() + "'";
          idb.delete(ändring);
         
          String nyRas = "INSERT INTO " + ComboBoxVäljNyRas.getSelectedItem() + " (Alien_ID) " +  "VALUES" + "('" + ComboBoxVäljAlien.getSelectedItem()+ "')";
          idb.insert(nyRas);
       }
       if(ComboBoxVäljNuvarandeRas.getSelectedItem().equals("Squid")){
          String ändring = "DELETE FROM Squid where Alien_ID = '" + ComboBoxVäljAlien.getSelectedItem() + "'";
          idb.delete(ändring);
          
          String nyRas = "INSERT INTO " + ComboBoxVäljNyRas.getSelectedItem()+ "(Alien_ID)" + "VALUES" + "('" + ComboBoxVäljAlien.getSelectedItem()+ "')";
          idb.insert(nyRas);
          
       }
          
       LabelRasenHarÄndrats.setVisible(true);
       }
       catch(InfException e){
           JOptionPane.showMessageDialog(null, "Error");
       }
    }//GEN-LAST:event_ButtonÄndraActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ÄndraRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ÄndraRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ÄndraRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ÄndraRas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ÄndraRas(idb).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonÄndra;
    private javax.swing.JComboBox<String> ComboBoxVäljAlien;
    private javax.swing.JComboBox<String> ComboBoxVäljNuvarandeRas;
    private javax.swing.JComboBox<String> ComboBoxVäljNyRas;
    private javax.swing.JLabel LabelNuvarandeRas;
    private javax.swing.JLabel LabelRasenHarÄndrats;
    private javax.swing.JLabel LabelRubrik;
    private javax.swing.JLabel LabelVäljAlien;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
